"""Proves an agent's answer text is generated by the update system
(scripts/build_label.py pulling live openFDA), not a prewritten passage
sitting in the repo.

For each drug: delete labels/<drug>.json outright (so nothing prewritten is
left to fall back on), call the same refresh_if_stale() an agent process
calls on startup/every REFRESH_CHECK_HOURS, then boot the real agent app on
whatever that call produced and hit its live /answer endpoint. Every returned
passage is checked against an INDEPENDENTLY re-fetched copy of the live SPL,
so nothing here can be satisfied by a value baked into the test itself.
The original label file is restored afterward either way.

Needs network access to https://api.fda.gov.

    .venv/bin/python -m tests.test_live_refresh
"""

from __future__ import annotations

import asyncio
import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from brand_agent.service import build_app  # noqa: E402
from scripts.build_label import KNOWN, refresh_if_stale  # noqa: E402

LABELS = {drug: ROOT / "labels" / f"{drug}.json" for drug in KNOWN}
QUESTIONS = {
    "simvastatin": "What are the contraindications for simvastatin?",
    "clarithromycin": "What are the contraindications for clarithromycin?",
}

PASSED: list[str] = []
FAILED: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    (PASSED if ok else FAILED).append(f"{name}{(' - ' + detail) if detail else ''}")


def fetch_live_spl(spl_id: str) -> dict:
    query = urllib.parse.quote(f'id:"{spl_id}"')
    url = f"https://api.fda.gov/drug/label.json?search={query}&limit=1"
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.load(response)["results"][0]


async def check_drug(drug: str, path: Path) -> None:
    backup = path.read_text() if path.exists() else None
    try:
        if path.exists():
            path.unlink()
        rebuilt = refresh_if_stale(drug)
        check(f"{drug}: update system rebuilt the label with nothing prewritten on disk", rebuilt)
        check(f"{drug}: label file exists after rebuild", path.exists())
        if not path.exists():
            return

        generated = json.loads(path.read_text())

        # Independently re-fetch the SPL (a second, separate network call) so
        # nothing here can be satisfied by a value the test itself supplied.
        record = fetch_live_spl(generated["_meta"]["spl_id"])
        mismatched = []
        for section in generated["sections"]:
            field = section["source"]["field"]
            source_text = " ".join(" ".join(record[field]).split())
            if section["text"] not in source_text:
                mismatched.append(section["section"])
        check(f"{drug}: every generated passage is verbatim in live openFDA (not invented)",
              not mismatched, str(mismatched))

        # Boot the real agent app on exactly what the update system just wrote,
        # and confirm what it SERVES over HTTP traces back to that, not to some
        # other static source (e.g. a leftover mock/placeholder string).
        app = build_app(path, domain="scriptsync.health")
        transport = httpx.ASGITransport(app=app)
        async with httpx.AsyncClient(transport=transport, base_url="http://agent") as client:
            answer = (await client.post("/answer", json={"question": QUESTIONS[drug]})).json()
        check(f"{drug}: agent answered the question", not answer.get("refused"),
              str(answer.get("reason")))
        generated_texts = {s["text"] for s in generated["sections"]}
        served_texts = {a["text"] for a in answer.get("answers", [])}
        check(f"{drug}: served answer text is exactly what the update system generated",
              bool(served_texts) and served_texts <= generated_texts,
              str(served_texts - generated_texts))
    finally:
        if backup is not None:
            path.write_text(backup)
        elif path.exists():
            path.unlink()


async def main_async() -> None:
    for drug, path in LABELS.items():
        await check_drug(drug, path)


def main() -> None:
    asyncio.run(main_async())
    print("\n".join(f"  PASS  {p}" for p in PASSED))
    if FAILED:
        print("\n".join(f"  FAIL  {f}" for f in FAILED))
    print(f"\n{len(PASSED)} passed, {len(FAILED)} failed")
    raise SystemExit(1 if FAILED else 0)


if __name__ == "__main__":
    main()
